### ISSUE TITLE
EventChange implementation mistakes

### ISSUE THREAD

**Issue by Gerard097** [Equilibrium-Games/Acid#22]
EventChange isn't properly implemented. As a template class, it should have its methods defined in the same file that was declared, or including the .inl (cpp) at the end of the file (hpp).

Also the EventTriggered has a typo i guess.

`T newValue = &m_reference; //&`

I think that the real intention was to obtain the value of the reference

`T newValue = *m_reference; //*`

and also the if (newValue == nullptr) has no sense in this context.

Notice that this implementation will only notify one change if any per frame. I'd recommend also adding another method to achieve this kind of behavior but for every change like an Observer-Subject pattern or wrapping the change value inside a class as suggested in this SO https://stackoverflow.com/a/3159198/7908019.

**Comment by mattparks** [comment]
Thanks for finding this issue, should now be fixed with https://github.com/Equilibrium-Games/Acid/commit/777db1cb157a255ae09f773546ee01322a54c361. A assignment hook is probably not needed for this event type as it is used to check if the value is different from the last update time, not if it has ever had a change between the updates.
